### ISSUE TITLE
empty result for example?

### ISSUE THREAD

**Issue by jhercher** [tomav/node-microdata-scraper#3]
Hi, 

I installed and created a file `example.js` with the example code in it:

```
var microdata = require('node-microdata-scraper');
var url       = 'https://raw.github.com/mhausenblas/schema-org-rdf/master/examples/Thing/Product/Product.microdata';
microdata.parseUrl(url, function(err, json) {
  if (!err && json) {
    console.log("hello world");
    console.log(json);
  }
});
```
when I run `node example.js` all I get is an empty array:
```
[]
```
I checked the URL from the example which is still online. Also, I can see my own `console.log("hello world")` in the callback function. Are I'm doing sth. wrong here?

Cheers,
Johannes

**Comment by tomav** [comment]
Hi @jhercher, let me know if it works now.

**Comment by jhercher** [comment]
Hi tomav,

now I get an error:

```
$ node example.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'node-microdata-scraper'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Volumes/#/#/#/node-microdata-scraper/example.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by tomav** [comment]
`node-microdata-scraper` is missing as you can see in the error message.
Try `npm install node-microdata-scraper` before you retry.

**Comment by jhercher** [comment]
Ah, Thanks! It's working now.
